document.write( '<nav class=\"navbar navbar-expand-lg navbar-default\" style=\"background-image: url(images/nav-bg.jpg);\">                                                                                                                                        \n' );
document.write( '    <a class=\"navbar-brand\" href=\"\">Whisked</a>\n' );
document.write( '    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarTogglerDemo\">\n' );
document.write( '        <span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '    </button>\n' );
document.write( '    <div class=\"collapse navbar-collapse\" id=\"navbarToggler\">\n' );
document.write( '        <ul class=\"navbar-nav ml-auto\">\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"#footer\">Sell</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"store.html\">Store</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"about.html\">About</a>\n' );
document.write( '            </li>\n' );
document.write( '        </ul>\n' );
document.write( '    </div>\n' );
document.write( '</nav>\n' );

